name: CI

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: CMake configuration
        run: cmake -S . -B build
      - name: Building
        run: cmake --build build
      - name: Testing
        run: ctest --test-dir build

  build-windows:
    runs-on: windows-latest
   
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: CMake configuration
        run: cmake -S . -B build
      - name: Building
        run: cmake --build build
      - name: Testing
        run: ctest --test-dir build
